### ISSUE TITLE
Editing the region instead of the string?

### ISSUE THREAD

**Issue by grettke** [magnars/string-edit.el#8]
Good afternoon,

Today I am fixing a deficit in a Yas snippet I wrote. The way Yas snippets
work is by template expansion. They are great; easy and powerful. Here is what
I am working on; it just enforces available languages in org-mode source blocks.

    #+NAME: ${1:`(org-id-new)`}
    #+BEGIN_SRC ${2:$$(yas-choose-value (sort (-map (lambda (x) (symbol-name (car x))) org-babel-load-languages) 'string<))}${2:$(when (-contains? '("ditaa" "dot" "plantuml") yas-text) (concat " :file \\"./image/" (yas-field-value 1) ".png\\""))} $3
    $0
    #+END_SRC

It didn&rsquo;t start out like that, it used to short. Now the template is long and
it is difficult to end. I want it to be easy again. What I would really like to
do is to:

-   Select the Emacs-Lisp code
-   Open it up in a new buffer
-   Re-indent it so it is easily readable
-   Do my work
-   Close that buffer and copy the contents back to one line

That made me think of string-edit. They are so similar.

I also thought about doing something like [this](https://www.wisdomandwonder.com/link/8610/lightweight-multiple-modes-for-semi-literate-programming).

Have you ever need to do something like this? If you did, what approach did you
follow? I don&rsquo;t want to reinvent the wheel and I&rsquo;m guessing that this has been
done before; editing code that lives on a single. The other example is when you
have file local variable eval line.

cheers

**Comment by magnars** [comment]
Hello!

Yes, that workflow sounds familiar. string-edit itself is very much about strings, but I'm sure it could be hammered into something that works with this too. I wouldn't want to do it in the current code base tho.

As for how I would do something like it. I have a keybinding to open a scratch buffer in emacs-lisp mode that I use a lot. For me it's on C-c b, and it looks like this:

```el
(defun create-scratch-buffer nil
  "create a new scratch buffer to work in. (could be *scratch* - *scratchX*)"
  (interactive)
  (let ((n 0)
        bufname)
    (while (progn
             (setq bufname (concat "*scratch"
                                   (if (= n 0) "" (int-to-string n))
                                   "*"))
             (setq n (1+ n))
             (get-buffer bufname)))
    (switch-to-buffer (get-buffer-create bufname))
    (emacs-lisp-mode)
    ))
```

I would paste the code into this throw-away buffer and then do the work there.

**Comment by grettke** [comment]
Gotcha. OK, we have two examples of doing something kinda similar. Just isn't enough to justify refactoring yet for me. Until then I've got one, too that I can tweak:

https://www.wisdomandwonder.com/link/8610/lightweight-multiple-modes-for-semi-literate-programming

I'm just waiting for the thousands out there who will us know of the urgent need for such a mode.

**Comment by Fuco1** [comment]
@grettke You might enjoy https://github.com/Fanael/edit-indirect

**Comment by grettke** [comment]
Thank you @Fuco1 .
